/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_byhook_code_GaussBlurry */

#ifndef _Included_cn_byhook_code_GaussBlurry
#define _Included_cn_byhook_code_GaussBlurry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onzhou_graphic_GaussBitmap
 * Method:    gaussBitmap
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT jint JNICALL Java_com_onzhou_graphic_GaussBitmap_gaussBitmap
  (JNIEnv *, jobject, jobject,jint radius);

/**
 * 高斯模糊算法
 **/
void GaussBitmap(int* pix, int w, int h, int radius);

#ifdef __cplusplus
}
#endif
#endif