/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_opengles_color_NativeColorRenderer */

#ifndef NATIVE_YUV2JPEG_H
#define NATIVE_YUV2JPEG_H
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL loadPNGImage(JNIEnv *, jobject, jstring, jobject);


#ifdef __cplusplus
}
#endif
#endif
